---
title: "MÍNIMOS QUADRADOS ORDINÁRIOS: UMA APLICAÇÃO NA ANÁLISE DAS QUESTÕES INSTITUCIONAIS DE MUNICÍPIOS BRASILEIROS"
institution: "UNIVERSIDADE FEDERAL DE MINAS GERAIS"
advisor: "Ana Hermeto"
city: "Belo Horizonte"
state: "MG"
month: "Abril"
year: 2024
author:
    - name: "Flávio Hugo Pangracio Silva"
      orcid: 0000-0003-4045-101X
      email: "flaviopangracio@cedeplar.ufmg.br"
      affiliations:
        - name: "Cedeplar - UFMG"
          url: https://cedeplar.ufmg.br

    - name: "Guilherme Gomes Ferreira"
      orcid: 0009-0006-5032-8997
      email: "guilhermegf2019@cedeplar.ufmg.br"
      affiliations:
        - name: "Cedeplar - UFMG"
          url: https://cedeplar.ufmg.br
bibliography: referencies/ref.bib
csl: cite_styles/abnt.csl
highlight-style: kate
fig-cap-location: top
lang: pt-BR
license: "This work is dedicated to the Public Domain"
format:
    pdf:
        template-partials:
            - tex_files/_print-author.tex
            - tex_files/doc-class.tex
            - tex_files/before-body.tex
        mainfont: "Times New Roman"
---

\pagestyle{fancy} <!-- Show the page number --> \justify
\onehalfspacing

# INTRODUÇÃO

O presente trabalho se propõe a explorar de maneira detalhada o método de mínimos quadrados ordinários (MQO), apresentando uma aplicação na análise das questões institucionais presentes nos municípios brasileiros. Este método estatístico é amplamente utilizado na análise econômica, sendo fundamental para compreender as relações entre variáveis e realizar previsões.

A escolha desse enfoque se justifica pela relevância crescente do estudo das instituições no contexto municipal brasileiro, visto que as políticas públicas e a gestão eficiente dessas instituições desempenham um papel fundamental no desenvolvimento socioeconômico local. Nesse sentido, compreender como diferentes variáveis institucionais estão relacionadas entre si e como influenciam indicadores de crescimento e desenvolvimento municipal torna-se uma questão de interesse.

Por meio deste trabalho, pretendemos não apenas apresentar a aplicação prática do modelo de MQO, mas também fornecer uma base sólida de compreensão teórica, destacando os fundamentos matemáticos e estatísticos subjacentes a esse método. Para isso, organizaremos o conteúdo em várias seções, nas quais abordaremos desde os princípios básicos da regressão linear até aspectos mais avançados, passando pela discussão sobre a formulação teórica do modelo de MQO.

Inicialmente, abordaremos os principais conceitos e definições relacionados à regressão linear, discutindo os pressupostos e as limitações desse modelo estatístico. Posteriormente, dedicaremos atenção especial à formulação teórica do modelo de MQO, descrevendo o processo de estimativa dos parâmetros e apresentando as principais propriedades estatísticas dos estimadores obtidos por esse método. Além disso, discutiremos técnicas de diagnóstico e avaliação da qualidade do modelo, destacando a importância da interpretação correta dos resultados obtidos.

Por fim, demonstraremos a aplicação do modelo de MQO na análise das questões institucionais de municípios brasileiros, utilizando dados da REGIC para ilustrar o processo de formulação, estimação e interpretação do modelo. Espera-se que este trabalho contribua para ampliar o entendimento sobre o método de MQO e sua aplicação.

@heiss
@greene

\newpage

# REFERÊNCIAS

\singlespacing

::: {#refs}
:::